version: '3'
services:
  redis:
      container_name: redis
      image: redis
      restart: always
      command: /bin/sh -c "redis-server /usr/local/etc/redis/redis.conf"
      volumes:
        - ./redis-data:/data
        - ./redis.conf:/usr/local/etc/redis/redis.conf
      logging:
        options:
          max-size: "50M"
          max-file: "3"